# Generated by Django 3.0.5 on 2020-04-03 20:10

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
