# Generated by Django 2.2 on 2020-06-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagslug', models.SlugField()),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='blog_picture'),
        ),
        migrations.AlterField(
            model_name='author',
            name='profile_background_picture',
            field=models.ImageField(upload_to='profile_background_picture'),
        ),
        migrations.AlterField(
            model_name='author',
            name='profile_picture',
            field=models.ImageField(upload_to='profile_picture'),
        ),
    ]
